name: Deploy Node App to Namecheap

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # IMPORTANT: install dev deps for build
      - name: Install deps (includes dev)
        run: npm ci --include=dev

      - name: Build (Next.js)
        run: npm run build

      - name: Upload to server (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./"
          remote_path: ${{ secrets.REMOTE_DIR }}
          exclude: |
            .git*
            .github*
            node_modules
            .next/cache
            **/*.log
            coverage
            tmp
            dist/*.map

      - name: Install/Build/Restart on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.REMOTE_DIR }}
            mkdir -p tmp

            # Build requires dev deps too
            npm ci --include=dev
            npm run build

            # Optional: slim down after build
            npm prune --omit=dev

            touch tmp/restart.txt
            echo "Deployment complete ✅"
