name: Deploy Node App to Namecheap

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies (includes dev)
        run: npm ci --include=dev

      - name: Build (Next.js)
        run: npm run build

      - name: Prepare deploy bundle
        run: |
          set -e
          rm -rf deploy
          mkdir -p deploy
          cp -r .next deploy/.next
          [ -d public ] && cp -r public deploy/public || true
          [ -f server.js ] && cp server.js deploy/server.js || true
          [ -f server.mjs ] && cp server.mjs deploy/server.mjs || true
          [ -f next.config.js ] && cp next.config.js deploy/ || true
          [ -f next.config.mjs ] && cp next.config.mjs deploy/ || true
          cp package.json deploy/package.json
          [ -f package-lock.json ] && cp package-lock.json deploy/package-lock.json || true

      # Upload deploy/ via SCP using INLINE KEY (no key_path)
      - name: Upload deploy bundle via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }} # 21098 on Namecheap shared
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "${{ secrets.REMOTE_DIR }}"
          overwrite: true
          strip_components: 1

      # Install prod deps on server & restart Passenger (INLINE KEY)
      - name: Install runtime deps & restart app (SSH)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.REMOTE_DIR }}
            mkdir -p tmp
            npm ci --omit=dev
            touch tmp/restart.txt
            echo "Deployment complete ✅"
