name: Deploy Node App to Namecheap.com

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > ~/.ssh/gh_actions
          chmod 600 ~/.ssh/gh_actions

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Install dev deps for build (Tailwind/PostCSS, etc.)
      - name: Install deps (includes dev)
        run: npm ci --include=dev

      - name: Build (Next.js)
        run: npm run build

      # Prepare minimal deploy artifact
      - name: Prepare deploy bundle
        run: |
          set -e
          rm -rf deploy
          mkdir -p deploy
          # Core runtime assets for Next.js SSR
          cp -r .next deploy/.next
          [ -d public ] && cp -r public deploy/public || true
          # App entry / config files (adjust as needed)
          [ -f server.js ] && cp server.js deploy/server.js || true
          [ -f server.mjs ] && cp server.mjs deploy/server.mjs || true
          [ -f next.config.js ] && cp next.config.js deploy/ || true
          [ -f next.config.mjs ] && cp next.config.mjs deploy/ || true
          # Package manifests for runtime install
          cp package.json deploy/package.json
          if [ -f package-lock.json ]; then cp package-lock.json deploy/package-lock.json; fi

      # Upload deploy/ to your app directory
      - name: Upload via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/*"
          target: "${{ secrets.REMOTE_DIR }}"
          overwrite: true
          strip_components: 1

      # Install runtime deps & restart Passenger
      - name: Install runtime deps & restart
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.REMOTE_DIR }}
            mkdir -p tmp
            # Install ONLY production deps
            npm ci --omit=dev
            # If you run with "next start":
            # npx next telemetry disable >/dev/null 2>&1 || true
            # Signal Passenger to reload
            touch tmp/restart.txt
            echo "Deployment complete ✅"
